---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install checks for openstack cinder-api
  hosts: cinder_api
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:
    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:

    - name: Install cinder api checks
      template:
        src: "templates/rax-maas/cinder_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when: 'physical_host != ansible_host'

    - name: Install cinder api checks
      template:
        src: "templates/rax-maas/cinder_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when: 'physical_host == ansible_host'

    - name: Install cinder lb checks
      template:
        src: "templates/rax-maas/lb_api_check_cinder.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_cinder.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - 'physical_host != ansible_host'
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install cinder lb checks
      template:
        src: "templates/rax-maas/lb_api_check_cinder.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_cinder.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - 'physical_host == ansible_host'
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install cinder private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_cinder.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_cinder.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - 'physical_host != ansible_host'
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

    - name: Install cinder private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_cinder.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_cinder.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - 'physical_host == ansible_host'
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-cinder


- name: Install checks for openstack cinder-api
  hosts: cinder_scheduler
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:
    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Install cinder api checks
      template:
        src: "templates/rax-maas/cinder_scheduler_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_scheduler_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when: 'physical_host != ansible_host'

    - name: Install cinder api checks
      template:
        src: "templates/rax-maas/cinder_scheduler_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_scheduler_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when: 'physical_host == ansible_host'

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-cinder


- name: Install checks for openstack cinder-backup
  hosts: cinder_backup
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:
    - include_tasks: "common-tasks/maas_excluded_regex.yml"

    - name: Stop deployment of cinder backup
      block:
        - name: Notify
          debug:
            msg: >-
              No suitable backed was available for cinder backup to run. This check will not be deployed.

        - name: Exit
          meta: end_play
      when:
        - (((groups['swift_all'] | default([])) | union(groups['rgws'] | default([]))) | length) < 1

  tasks:
    - name: Install cinder backup checks
      template:
        src: "templates/rax-maas/cinder_backup_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_backup_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - 'physical_host != ansible_host'
        - ansible_local['maas']['general']['maas_monitor_cinder_backup'] | bool

    - name: Install cinder backup checks
      template:
        src: "templates/rax-maas/cinder_backup_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_backup_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - 'physical_host == ansible_host'
        - ansible_local['maas']['general']['maas_monitor_cinder_backup'] | bool

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-cinder


- name: Install checks for openstack cinder-volume
  hosts: cinder_volume
  gather_facts: true
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  pre_tasks:
    - include_tasks: "common-tasks/maas_excluded_regex.yml"

    - name: Set cinder backend facts
      set_fact:
        maas_cinder_local_backends: "{{ ansible_local.maas.cinder.local_backends | default([]) }}"
        maas_cinder_shared_backends: "{{ ansible_local.maas.cinder.shared_backends | default([]) }}"

  tasks:
    - name: Install cinder volume local checks
      template:
        src: "templates/rax-maas/cinder_volume_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_volume_{{ item.split('@')[-1] }}_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      with_items:
        - "{{ maas_cinder_local_backends }}"
      when:
        - 'physical_host != ansible_host'
        - (item.split('@')[0] | replace('-', '_')) in (inventory_hostname | replace('-', '_'))

    - name: Install cinder volume local checks
      template:
        src: "templates/rax-maas/cinder_volume_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_volume_{{ item.split('@')[-1] }}_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - "{{ maas_cinder_local_backends }}"
      when:
        - 'physical_host == ansible_host'
        - (item.split('@')[0] | replace('-', '_')) in (inventory_hostname | replace('-', '_'))

    - name: Install cinder volume shared checks
      template:
        src: "templates/rax-maas/cinder_volume_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_volume_{{ item.split('@')[-1] }}_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      with_items:
        - "{{ maas_cinder_shared_backends }}"
      when:
        - 'physical_host != ansible_host'
        - inventory_hostname == groups['cinder_volume'][0]
        - item.split('@')[0] != 'ceph'

    - name: Install cinder volume shared checks
      template:
        src: "templates/rax-maas/cinder_volume_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_volume_{{ item.split('@')[-1] }}_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - "{{ maas_cinder_shared_backends }}"
      when:
        - 'physical_host == ansible_host'
        - inventory_hostname == groups['cinder_volume'][0]
        - item.split('@')[0] != 'ceph'

    - name: Install cinder volume legacy ceph cluster check
      template:
        src: "templates/rax-maas/cinder_volume_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_volume_{{ item.key }}_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      with_dict: "{{ cinder_backends | default({}) }}"
      when:
        - "'volume_driver' in cinder_backends[item.key]"
        - inventory_hostname == groups['cinder_volume'][0]
        - ('ceph@ceph' in maas_cinder_shared_backends and ansible_local['maas']['general']['maas_product_osa_version'] is defined)

    - name: Install cinder vg checks
      template:
        src: "templates/rax-maas/cinder_vg_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_vg_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      with_dict: "{{ cinder_backends | default({}) }}"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - 'physical_host != ansible_host'
        - "'volume_group' in cinder_backends[item.key]"

    - name: Install cinder vg checks
      template:
        src: "templates/rax-maas/cinder_vg_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_vg_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      with_dict: "{{ cinder_backends | default({}) }}"
      when:
        - 'physical_host == ansible_host'
        - "'volume_group' in cinder_backends[item.key]"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-cinder
