---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install checks for octavia
  hosts: "octavia_all"
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  gather_facts: true
  pre_tasks:
    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Set OSA rc file fact
      set_fact:
        rc_file_location: "{{ maas_openrc | default('/root/openrc') }}"
      when:
        - not (ansible_local.maas.general.deploy_osp | bool)

    - name: Set OSP rc file fact
      set_fact:
        rc_file_location: "{{ maas_stackrc | default(maas_openrc) }}"
      when:
        - ansible_local.maas.general.deploy_osp | bool

    - name: Get Octavia project ID
      shell: |-
        . {{ rc_file_location }}
        openstack project show service -c id -f value
      register: octavia_project_return
      delegate_to: "{{ groups['utility_all'][0] }}"
      tags:
        - skip_ansible_lint

    - name: Set Octavia project ID
      set_fact:
        octavia_project_id: "{{ octavia_project_return.stdout }}"

    - name: Install octavia process check
      template:
        src: "templates/rax-maas/octavia_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when: 'physical_host != ansible_host'

    - name: Install octavia process check
      template:
        src: "templates/rax-maas/octavia_process_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_process_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when: 'physical_host == ansible_host'

    - name: Install octavia quota check
      template:
        src: "templates/rax-maas/octavia_quota_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_quota_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when: 'physical_host != ansible_host'

    - name: Install octavia quota check
      template:
        src: "templates/rax-maas/octavia_quota_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_quota_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when: 'physical_host == ansible_host'

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - maas-openstack-octavia

- name: Install checks for openstack octavia API
  hosts: "octavia-api:octavia_api"
  user: "{{ ansible_ssh_user | default('root') }}"
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: "{{ target_venv | default(maas_venv) }}/bin/python"
  pre_tasks:
    - include_tasks: "common-tasks/maas_excluded_regex.yml"

  tasks:
    - name: Ensure the observer role exists
      os_keystone_role:
        cloud: "{{ cloud_config_name }}"
        interface: "{{ keystone_check_interface }}"
        name: "{{ octavia_observer_role_name }}"
        state: present
      delegate_to: localhost
      run_once: true

    - name: Ensure Octavia observer member role assignment
      os_user_role:
        cloud: "{{ cloud_config_name }}"
        interface: "{{ keystone_check_interface }}"
        role: "{{ octavia_observer_role_name }}"
        domain: "{{ octavia_project_domain }}"
        project: "{{ octavia_project }}"
        user: "{{ octavia_user }}"
        state: present
      delegate_to: localhost
      run_once: true

    - name: Install octavia api checks
      template:
        src: "templates/rax-maas/octavia_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when: 'physical_host != ansible_host'

    - name: Install octavia api checks
      template:
        src: "templates/rax-maas/octavia_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/octavia_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when: 'physical_host == ansible_host'

    - name: Install octavia lb checks
      template:
        src: "templates/rax-maas/lb_api_check_octavia.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_octavia.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - 'physical_host != ansible_host'
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install octavia lb checks
      template:
        src: "templates/rax-maas/lb_api_check_octavia.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_octavia.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - 'physical_host == ansible_host'
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install octavia private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_octavia.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_octavia.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - 'physical_host != ansible_host'
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

    - name: Install octavia private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_octavia.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_octavia.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - 'physical_host == ansible_host'
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - maas-openstack-octavia
